const paragraphs = [
    "Bengaluru-based insurtech startup Digit Insurance was the first startup to enter the Indian unicorn club in 2021. The company had raised $18 Mn (INR 135 Cr) from existing investors A(! PArtners, Faering Capital and TVS Capital in January, at a valuation of $1.9 Bn.This was the company’s second external funding round, the first one coming in January 2020. The company had raised $84 Mn (INR 614 Cr at the current conversion rate) as a part of this round.",
    "The strain on global healthcare due to Covid-19 was enormous and shocking with the fear of mass infection hanging over the public. If not for the healthcare providers putting in the extra effort to ensure smooth recovery of those infected, the global tally of deaths would have been significantly higher. As the world stepped into lockdown, healthcare became of utmost importance as did solutions for the sector.",
    "The Indian social commerce segment may be at a nascent stage at this point but it is poised to grow at a compound annual growth rate (CAGR) of 55%-60% to reach $16 Bn-$20 Bn gross merchandise value (GMV) by 2025. One of the biggest milestones of the segment has to be Meesho’s entry into the unicorn club, which will have an overall impact on the segment and its growth momentum.Founded by IIT-Delhi graduates Aatrey and Sanjeev Barnwal in 2015, Meesho is an online reseller network.",
    "There are very few Indian unicorns that have maintained profitability from the very beginning. This year, there was another such startup, Infra.Market, that entered the club riding on its profitability and strong growth. The company, founded by Aaditya Sharda and Souvik Sengupta in 2016, is a B2B online procurement marketplace for real estate and construction material that leverages technology to offer fair pricing and a smoother procurement experience for its customers.",
    "With eyes on market dominance and the unicorn club, API Holdings had set out to forge a merger between its subsidiary PharmEasy and its rival Medlife in 2020. After the merger came through in the latter part of last year, the company was able to achieve one of its goals — entering the unicorn club. The company raised $323 Mn in a Series E funding round, at a valuation of $1.5 Bn. Notably, it is the first Indian epharmacy unicorn.",
    "With only INR 57 Lakh ($76K, at current conversion rate) as operating revenue in the financial year 2020, Kunal Shah-led fintech platform CRED entered the unicorn club at a whopping valuation of $2.2 Bn.Several big names of the VC ecosystem like DST Global, RTP Global, Tiger Global, Greenoaks Capital, Dragoneer Investment Group and Sofina has placed their bets over CRED, which focuses on premium credit card users, offering them rewards and benefits for paying credit card bills.",
    "India found its second wealth management unicorn in Groww only eight months after bootstrapped Zerodha valued itself above $1 Bn. Just like Zerodha, Groww allows users to invest in stocks, mutual funds, ETFs, IPOs, and Gold using its tech platform available via mobile application and web platform. The company had also launched stocks with an easy-to-use interface for do-it-yourself (DIY) investors.",
    "ShareChat has finally found its way to the unicorn club, after capturing the attention of users across Tier II and III India. The regional language social media startup has witnessed massive growth in 2020, as its monthly active user base grew 166% from 60 Mn to 160 Mn in one year. The most interesting trend that the startup witnessed was that it stepped out of its comfort zone in Tier II and Tier III regions of India and started garnering attention in Tier I and metro cities during the pandemic, without having an English interface.",
];
    